---
version: 2.0

jobs:
  go:
    docker:
      - image: soon/protoc.go:latest
    environment:
      - CODEGEN_DIR: /codegen
    steps:
      - checkout
      - run:
          name: Deploy Key
          command: |
            cat <<EOT >> /tmp/git.sh
            #!/bin/sh
            ssh -i "\$GIT_SSH_KEY" "\$@"
            EOT
            chmod +x /tmp/git.sh
            echo "$GO_DEPLOY_KEY" | base64 -d > /tmp/go.id_rsa
            chmod 0600 /tmp/go.id_rsa
      - run:
          name: Clone proto.go
          environment:
            GIT_SSH: /tmp/git.sh
            GIT_SSH_KEY: /tmp/go.id_rsa
          command: |
              git clone git@github.com:thisissoon-fm/proto.go.git $CODEGEN_DIR
      - run:
          name: Generate Go Proto Code
          command: make go
      - run:
          name: Sync Generated Code
          command: |
            cp VERSION $CODEGEN_DIR/VERSION
            rsync -a -v -I --delete --exclude 'README.md' .codegen/go/github.com/thisissoon-fm/proto.go/* $CODEGEN_DIR
      - run:
          name: Commit Changes
          working_directory: /codegen
          environment:
            GIT_SSH: /tmp/git.sh
            GIT_SSH_KEY: /tmp/go.id_rsa
          command: |
            ssh-add -D
            ssh-add $GIT_SSH_KEY
            git config user.email "dorks+circleci@thisissoon.com"
            git config user.name "CircleCI"
            echo `git add -A && git commit -m "Code gen from proto repo @ $CIRCLE_SHA1"`
            git tag $(head -n 1 VERSION | tr -d "\n")
            git push origin
            git push origin --tags

  python2.7:
    docker:
      - image: soon/protoc.py27:latest
    environment:
      - CODEGEN_DIR: /codegen
    steps:
      - checkout
      - run:
          name: Deploy Key
          command: |
            cat <<EOT >> /tmp/git.sh
            #!/bin/sh
            ssh -i "\$GIT_SSH_KEY" "\$@"
            EOT
            chmod +x /tmp/git.sh
            echo "$PY27_DEPLOY_KEY" | base64 -d > /tmp/py27.id_rsa
            chmod 0600 /tmp/py27.id_rsa
      - run:
          name: Clone proto.py27
          environment:
            GIT_SSH: /tmp/git.sh
            GIT_SSH_KEY: /tmp/py27.id_rsa
          command: |
              git clone git@github.com:thisissoon-fm/proto.py27.git $CODEGEN_DIR
      - run:
          name: Generate Python2.7 Proto Code
          command: make py27
      - run:
          name: Sync Generated Code
          command: |
            cp VERSION $CODEGEN_DIR/VERSION
            rsync -a -v -I --delete --exclude 'README.md' .codegen/py27/* $CODEGEN_DIR
      - run:
          name: Commit Changes
          working_directory: /codegen
          environment:
            GIT_SSH: /tmp/git.sh
            GIT_SSH_KEY: /tmp/py27.id_rsa
          command: |
            ssh-add -D
            ssh-add $GIT_SSH_KEY
            git config user.email "dorks+circleci@thisissoon.com"
            git config user.name "CircleCI"
            echo `git add -A && git commit -m "Code gen from proto repo @ $CIRCLE_SHA1"`
            git tag $(head -n 1 VERSION | tr -d "\n")
            git push origin
            git push origin --tags

workflows:
  version: 2
  codegen:
    jobs:
      - go
      - python2.7
